"""Seed Trilium AI/LLM provider options into the options table.

Values arrive as arguments, so this is plain, lintable Python with no
templating involved. Backend facts come from a JSON config file
(generated by Nix, always valid); a secret API key arrives via --key-file
(LoadCredential friendly) instead of the config.

Two Trilium schemas are supported, detected at runtime from the option
rows present in the database, so the same config keeps working across
Trilium upgrades:

- 0.104.x: the ``experimentalFeatures`` array must contain ``"llm"``,
  and providers live in the ``llmProviders`` JSON array as
  ``{id, provider, apiKey, baseURL}`` entries (``openai-compatible``
  is the vLLM type). ``aiEnabled`` is derived from the feature flag.
- newer: ``aiEnabled``/``aiSelectedProvider`` plus per-provider
  ``BaseUrl``/``ApiKey``/``DefaultModel`` rows.

Exits 0 without touching anything when the database is not initialized
yet (fresh installs must complete the setup page first) or when all
values already match. Restarts trilium-server only when a value changed:
option reads go through the in-memory becca cache, so the server must
reload to see direct database writes.
"""

import argparse
import json
import os
import sqlite3
import subprocess
import sys
import time

POLL_ROUNDS = 60
POLL_DELAY = 2


def read_options(path):
    con = sqlite3.connect(path)
    try:
        con.execute("PRAGMA busy_timeout = 5000")
        return dict(con.execute("SELECT name, value FROM options").fetchall())
    finally:
        con.close()


def db_initialized(path):
    if not os.path.exists(path):
        return False
    try:
        return read_options(path).get("initialized") == "true"
    except sqlite3.Error:
        return False


def parse_str_list(raw):
    try:
        values = json.loads(raw or "[]")
    except (json.JSONDecodeError, TypeError):
        values = []
    return [v for v in values if isinstance(v, str)]


def parse_providers(raw):
    try:
        providers = json.loads(raw or "[]")
    except (json.JSONDecodeError, TypeError):
        providers = []
    return [p for p in providers if isinstance(p, dict)]


def legacy_rows(have, provider_id, provider_type, base_url, key):
    features = parse_str_list(have.get("experimentalFeatures"))
    if "llm" not in features:
        features.append("llm")
    entry = {
        "id": provider_id,
        "provider": provider_type,
        "apiKey": key,
        "baseURL": base_url,
    }
    providers = [
        p
        for p in parse_providers(have.get("llmProviders"))
        if p.get("id") != provider_id
    ]
    providers.append(entry)
    return [
        ("experimentalFeatures", json.dumps(features), True),
        ("llmProviders", json.dumps(providers), True),
    ]


def new_style_rows(provider, base_url, model, key):
    table = {
        "openai": ("openaiBaseUrl", "openaiApiKey", "openaiDefaultModel"),
        "ollama": ("ollamaBaseUrl", None, "ollamaDefaultModel"),
        "anthropic": ("anthropicBaseUrl", "anthropicApiKey", "anthropicDefaultModel"),
    }[provider]
    rows = [
        ("aiEnabled", "true", True),
        ("aiSelectedProvider", provider, True),
        (table[0], base_url, True),
        (table[2], model, True),
    ]
    if table[1] is not None:
        rows.append((table[1], key, False))
    return rows


def write_rows(db_path, rows):
    con = sqlite3.connect(db_path)
    try:
        con.execute("PRAGMA busy_timeout = 5000")
        with con:
            con.executemany(
                "UPDATE options SET value = ? WHERE name = ?",
                [(v, n) for (n, v, _) in rows],
            )
            con.executemany(
                "INSERT INTO options (name, value, isSynced) "
                "SELECT ?, ?, ? WHERE NOT EXISTS (SELECT 1 FROM options WHERE name = ?)",
                [(n, v, 1 if s else 0, n) for (n, v, s) in rows],
            )
    finally:
        con.close()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", required=True, help="Path to Trilium document.db.")
    parser.add_argument("--config", required=True, help="JSON file with backend facts.")
    parser.add_argument(
        "--key-file", help="File holding the API key (for keyFromFile configs)."
    )
    args = parser.parse_args()

    with open(args.config) as f:
        config = json.load(f)

    if config.get("keyFromFile"):
        if not args.key_file:
            print(
                "trilium-ai-config: config needs a key file but no --key-file was given.",
                file=sys.stderr,
            )
            sys.exit(1)
        with open(args.key_file) as f:
            key = f.read().rstrip("\n")
    else:
        key = config.get("apiKey", "")

    # Fresh installs only gain a database once the setup page is completed.
    for _ in range(POLL_ROUNDS):
        if db_initialized(args.db):
            break
        time.sleep(POLL_DELAY)
    else:
        print(
            "trilium-ai-config: database not initialized yet, skipping (retries next boot).",
            file=sys.stderr,
        )
        sys.exit(0)

    have = read_options(args.db)
    if "llmProviders" in have:
        rows = legacy_rows(
            have, config["providerId"], config["providerType"], config["baseUrl"], key
        )
    elif "aiSelectedProvider" in have:
        rows = new_style_rows(
            config["newProvider"], config["baseUrl"], config["model"], key
        )
    else:
        known = sorted(have)
        print(
            f"trilium-ai-config: unknown Trilium options schema (options: {known}).",
            file=sys.stderr,
        )
        sys.exit(1)

    if all(have.get(n) == v for (n, v, _) in rows):
        print("trilium-ai-config: AI options already match, nothing to do.")
        sys.exit(0)

    write_rows(args.db, rows)
    print(
        f"trilium-ai-config: seeded {len(rows)} AI options, restarting trilium-server."
    )
    subprocess.run(["systemctl", "restart", "trilium-server.service"], check=True)


if __name__ == "__main__":
    main()
